---
title: "Logicals"
author: "Daniel Kerstan"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



## Taking a look at `starwars`

- `include = ` : show or hide everything
- `echo = ` : show or hide code

```{r, include = FALSE}
summary(starwars)

head(starwars)

dim(starwars)

tail(starwars)


```


```{r, warning = FALSE}
ggplot(data = starwars, aes(x = height, y = mass)) + geom_point(color = "purple")
```


finding summary info for one column

```{r}
starwars$name
summary(starwars$height)
```

## Find the mean, variance and SD of character height

```{r}
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_mean
sw_height_variance <- var(starwars$height, na.rm = TRUE)
sw_height_variance
sw_height_sd <- sd(starwars$height, na.rm = TRUE)
sw_height_sd
```

Mean character height is `r round(sw_height_mean, 1)` cm, with a standard deviation of `r round(sw_height_sd, 1)` cm.


## Logical expressions

```{r}
5 < 10

"cat" > "armadillo"

"cat" > "elephant"

"dog" == "dog"

10 <= 11

5 >= 4

# vectors

tarantulas <- c(1, 3, 7, 15)

tarantulas > 5


```

## Logical operators

- `!` : not
- `&` : and
- `|` : or

```{r}

3 < 1 | 8 > 2

6< 10 & 5 < 1

7 != 11

4 != 4 | 2 < 5 | 6 > 10

0 == TRUE

0 == FALSE

1 == TRUE


```



